### PR TITLE
Update poll-form.html

### PR DESCRIPTION
**Pull request by CostGranda**
#11 It cand be done with the required attribute right?

### CODE REVIEW

**Review by robertoduessmann — APPROVED** [review]
Yep, that's good! Thanks for your contribution @CostGranda !

**Comment by CostGranda** [comment]
@robertoduessmann Nice! I think that atleast one option in the poll should be required too

**Comment by robertoduessmann** [comment]
Yeah, I agree with you @CostGranda, feel free to add this validation if you can ;)
I will open a issue for this.

**Comment by robertoduessmann** [comment]
Issue created: https://github.com/robertoduessmann/polling/issues/24

**Pull request merged**
